
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ARGUMENT ASSIGNMENT COMMENT CONTINUATION FOR INDENT KEYWORD NAME SEPARATOR SETTING SETTING_VALUEtestcases : testcase\n                    | testcases testcasetestcase : NAME\n                    | NAME body_itemsbody_items : body_item\n                      | body_items body_item\n        body_item : forloop\n                     | setting \n                     | step\n        setting : SETTING setting_valuessetting_values : SETTING_VALUE\n                          | setting_values SETTING_VALUEstep : KEYWORD\n                | KEYWORD argumentsstep : assignments KEYWORD\n                | assignments KEYWORD argumentsforloop : FOR arguments foritemsforitems : INDENT step\n                    | foritems INDENT step\n        assignments : ASSIGNMENT\n                     | assignments ASSIGNMENTarguments : ARGUMENT\n                     | arguments ARGUMENT'
    
_lr_action_items = {'NAME':([0,1,2,3,4,5,6,7,8,9,12,15,17,18,19,20,21,23,24,26,27,29,30,],[3,3,-1,-3,-2,-4,-5,-7,-8,-9,-13,-6,-22,-10,-11,-14,-15,-17,-23,-12,-16,-18,-19,]),'$end':([1,2,3,4,5,6,7,8,9,12,15,17,18,19,20,21,23,24,26,27,29,30,],[0,-1,-3,-2,-4,-5,-7,-8,-9,-13,-6,-22,-10,-11,-14,-15,-17,-23,-12,-16,-18,-19,]),'FOR':([3,5,6,7,8,9,12,15,17,18,19,20,21,23,24,26,27,29,30,],[10,10,-5,-7,-8,-9,-13,-6,-22,-10,-11,-14,-15,-17,-23,-12,-16,-18,-19,]),'SETTING':([3,5,6,7,8,9,12,15,17,18,19,20,21,23,24,26,27,29,30,],[11,11,-5,-7,-8,-9,-13,-6,-22,-10,-11,-14,-15,-17,-23,-12,-16,-18,-19,]),'KEYWORD':([3,5,6,7,8,9,12,13,14,15,17,18,19,20,21,22,23,24,25,26,27,28,29,30,],[12,12,-5,-7,-8,-9,-13,21,-20,-6,-22,-10,-11,-14,-15,-21,-17,-23,12,-12,-16,12,-18,-19,]),'ASSIGNMENT':([3,5,6,7,8,9,12,13,14,15,17,18,19,20,21,22,23,24,25,26,27,28,29,30,],[14,14,-5,-7,-8,-9,-13,22,-20,-6,-22,-10,-11,-14,-15,-21,-17,-23,14,-12,-16,14,-18,-19,]),'ARGUMENT':([10,12,16,17,20,21,24,27,],[17,17,24,-22,24,17,-23,24,]),'SETTING_VALUE':([11,18,19,26,],[19,26,-11,-12,]),'INDENT':([12,16,17,20,21,23,24,27,29,30,],[-13,25,-22,-14,-15,28,-23,-16,-18,-19,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'testcases':([0,],[1,]),'testcase':([0,1,],[2,4,]),'body_items':([3,],[5,]),'body_item':([3,5,],[6,15,]),'forloop':([3,5,],[7,7,]),'setting':([3,5,],[8,8,]),'step':([3,5,25,28,],[9,9,29,30,]),'assignments':([3,5,25,28,],[13,13,13,13,]),'arguments':([10,12,21,],[16,20,27,]),'setting_values':([11,],[18,]),'foritems':([16,],[23,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> testcases","S'",1,None,None,None),
  ('testcases -> testcase','testcases',1,'p_testcases','tcukparser.py',65),
  ('testcases -> testcases testcase','testcases',2,'p_testcases','tcukparser.py',66),
  ('testcase -> NAME','testcase',1,'p_testcase','tcukparser.py',70),
  ('testcase -> NAME body_items','testcase',2,'p_testcase','tcukparser.py',71),
  ('body_items -> body_item','body_items',1,'p_body_items','tcukparser.py',78),
  ('body_items -> body_items body_item','body_items',2,'p_body_items','tcukparser.py',79),
  ('body_item -> forloop','body_item',1,'p_body_item','tcukparser.py',94),
  ('body_item -> setting','body_item',1,'p_body_item','tcukparser.py',95),
  ('body_item -> step','body_item',1,'p_body_item','tcukparser.py',96),
  ('setting -> SETTING setting_values','setting',2,'p_setting','tcukparser.py',101),
  ('setting_values -> SETTING_VALUE','setting_values',1,'p_setting_values','tcukparser.py',105),
  ('setting_values -> setting_values SETTING_VALUE','setting_values',2,'p_setting_values','tcukparser.py',106),
  ('step -> KEYWORD','step',1,'p_step','tcukparser.py',110),
  ('step -> KEYWORD arguments','step',2,'p_step','tcukparser.py',111),
  ('step -> assignments KEYWORD','step',2,'p_step_with_assignment','tcukparser.py',118),
  ('step -> assignments KEYWORD arguments','step',3,'p_step_with_assignment','tcukparser.py',119),
  ('forloop -> FOR arguments foritems','forloop',3,'p_forloop','tcukparser.py',126),
  ('foritems -> INDENT step','foritems',2,'p_foritems','tcukparser.py',130),
  ('foritems -> foritems INDENT step','foritems',3,'p_foritems','tcukparser.py',131),
  ('assignments -> ASSIGNMENT','assignments',1,'p_assignments','tcukparser.py',140),
  ('assignments -> assignments ASSIGNMENT','assignments',2,'p_assignments','tcukparser.py',141),
  ('arguments -> ARGUMENT','arguments',1,'p_arguments','tcukparser.py',145),
  ('arguments -> arguments ARGUMENT','arguments',2,'p_arguments','tcukparser.py',146),
]
